cameron


In [6]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

np_array = np.array(data)
x_data = torch.from_numpy(np_array)

In [11]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(x_data)
print(x_ones)
print(x_rand)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.8770, 0.9981],
        [0.5567, 0.7818]])


In [13]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor\n {rand_tensor}")
print(f"Ones Tensor\n {ones_tensor}")
print(f"Zeros Tensor\n {zeros_tensor}")

Random Tensor
 tensor([[0.5490, 0.3925, 0.9993],
        [0.0035, 0.4278, 0.8714]])
Ones Tensor
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [17]:
dev = 'cpu'

tensor=torch.rand(4, 4).to(dev)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.7507, 0.6517, 0.3947, 0.8275])
First column: tensor([0.7507, 0.6730, 0.4508, 0.4305])
Last column: tensor([0.8275, 0.7688, 0.4832, 0.8740])
tensor([[0.7507, 0.0000, 0.3947, 0.8275],
        [0.6730, 0.0000, 0.8936, 0.7688],
        [0.4508, 0.0000, 0.1415, 0.4832],
        [0.4305, 0.0000, 0.1147, 0.8740]])


In [20]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[0.7507, 0.0000, 0.3947, 0.8275, 0.7507, 0.0000, 0.3947, 0.8275, 0.7507,
         0.0000, 0.3947, 0.8275],
        [0.6730, 0.0000, 0.8936, 0.7688, 0.6730, 0.0000, 0.8936, 0.7688, 0.6730,
         0.0000, 0.8936, 0.7688],
        [0.4508, 0.0000, 0.1415, 0.4832, 0.4508, 0.0000, 0.1415, 0.4832, 0.4508,
         0.0000, 0.1415, 0.4832],
        [0.4305, 0.0000, 0.1147, 0.8740, 0.4305, 0.0000, 0.1147, 0.8740, 0.4305,
         0.0000, 0.1147, 0.8740]])
torch.Size([4, 12])


In [19]:
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2)
print(t2.shape)

tensor([[[0.7507, 0.0000, 0.3947, 0.8275],
         [0.7507, 0.0000, 0.3947, 0.8275],
         [0.7507, 0.0000, 0.3947, 0.8275]],

        [[0.6730, 0.0000, 0.8936, 0.7688],
         [0.6730, 0.0000, 0.8936, 0.7688],
         [0.6730, 0.0000, 0.8936, 0.7688]],

        [[0.4508, 0.0000, 0.1415, 0.4832],
         [0.4508, 0.0000, 0.1415, 0.4832],
         [0.4508, 0.0000, 0.1415, 0.4832]],

        [[0.4305, 0.0000, 0.1147, 0.8740],
         [0.4305, 0.0000, 0.1147, 0.8740],
         [0.4305, 0.0000, 0.1147, 0.8740]]])


In [21]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(f'{y1 - y2} {y2 - y3} {y1 - y3}')


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [22]:

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.5635, 0.0000, 0.1558, 0.6848],
        [0.4529, 0.0000, 0.7985, 0.5911],
        [0.2033, 0.0000, 0.0200, 0.2335],
        [0.1853, 0.0000, 0.0132, 0.7638]])

In [24]:
print(tensor)
print(z1)
print(z1 - z2)

tensor([[0.7507, 0.0000, 0.3947, 0.8275],
        [0.6730, 0.0000, 0.8936, 0.7688],
        [0.4508, 0.0000, 0.1415, 0.4832],
        [0.4305, 0.0000, 0.1147, 0.8740]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [28]:
print((z1 - z2).sum(dim=1))
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([0., 0., 0., 0.])
tensor(6.8030)
6.802977561950684 <class 'float'>


In [29]:
print(tensor, "\n")
tensor.add_(5)
print(tensor, "\n")
tensor += 10
print(tensor, "\n")

tensor([[0.7507, 0.0000, 0.3947, 0.8275],
        [0.6730, 0.0000, 0.8936, 0.7688],
        [0.4508, 0.0000, 0.1415, 0.4832],
        [0.4305, 0.0000, 0.1147, 0.8740]]) 

tensor([[5.7507, 5.0000, 5.3947, 5.8275],
        [5.6730, 5.0000, 5.8936, 5.7688],
        [5.4508, 5.0000, 5.1415, 5.4832],
        [5.4305, 5.0000, 5.1147, 5.8740]]) 

tensor([[15.7507, 15.0000, 15.3947, 15.8275],
        [15.6730, 15.0000, 15.8936, 15.7688],
        [15.4508, 15.0000, 15.1415, 15.4832],
        [15.4305, 15.0000, 15.1147, 15.8740]]) 



In [30]:
tensor += torch.rand_like(tensor)
print(tensor, "\n")

tensor([[16.1123, 15.3795, 16.3821, 16.4317],
        [15.7846, 15.1699, 15.9288, 16.2827],
        [16.3425, 15.2435, 15.6169, 15.7586],
        [16.0835, 15.7345, 16.0430, 16.6115]]) 



In [32]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [33]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [34]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
